"""
 * (c) Copyright, Real-Time Innovations, 2022.  All rights reserved.
 * RTI grants Licensee a license to use, modify, compile, and create derivative
 * works of the software solely for use with RTI Connext DDS. Licensee may
 * redistribute copies of the software provided that all such copies are subject
 * to this license. The software is provided "as is", with no warranty of any
 * type, including any warranty for fitness for any purpose. RTI is under no
 * obligation to maintain or support the software. RTI shall not be liable for
 * any incidental or consequential damages arising out of the use or inability
 * to use the software.

 COMPILED TYPES VERSION
 ----------------------
 This version uses RTI Connext DDS compiled Python types (generated by
 rtiddsgen / @idl.struct decorators) instead of DynamicData.

 Key differences from the dynamic-types python/ version:
   - Writer and Reader accept a *type class* (e.g. tmsConstants.tms_Heartbeat)
     instead of a type-name string.
   - Data samples are plain Python dataclass instances (TypeClass()) rather
     than dds.DynamicData objects.
   - DataWriters are obtained via participant.find_datawriter() and wrapped
     with dds.DataWriter(); DataReaders similarly via dds.DataReader().
   - Field access uses Python attribute syntax (sample.field) rather than
     dict-style subscripts (sample["field"]).
   - dds.NoOpDataWriterListener replaces dds.DynamicData.NoOpDataWriterListener.
   - dds.ContentFilteredTopic.find() replaces the DynamicData-namespaced
     equivalent used in the dynamic version.

 GENERALLY, CODE IN THIS FILE SHOULD NOT BE MODIFIED AS IT HANDLES ALL OF THE
 GENERIC DDS INFRASTRUCTURE AND CREATES THREADS (and dds Waitsets)

 User Code (Topics in topics.py) Should Inherit a Reader or Writer and extend
 the class memberfunction handler to set/read topic specific data type fields.
 The user topic specific classes can also add data members and member functions
 as needed.
"""

from threading import Thread
import logging
from time import sleep
import constants
import application
import tmsConstants
import rti.connextdds as dds


# ---------------------------------------------------------------------------
# Type registration helper
# ---------------------------------------------------------------------------

def register_tms_types():
    """Register all TMS compiled types with the DDS runtime.

    Must be called BEFORE qos_provider.create_participant_from_config() so
    that the XML Application Creation machinery can bind each XML
    <register_type> entry to the corresponding Python @idl.struct class.

    The registered names must match the 'name' attribute used in the XML
    domain library's <register_type> elements (e.g. "tms::Heartbeat").
    """
    dds.DomainParticipant.register_idl_type(
        tmsConstants.tms_Heartbeat, "tms::Heartbeat")
    dds.DomainParticipant.register_idl_type(
        tmsConstants.tms_DeviceInfo, "tms::DeviceInfo")
    dds.DomainParticipant.register_idl_type(
        tmsConstants.tms_ActiveMicrogridControllerState,
        "tms::ActiveMicrogridControllerState")
    dds.DomainParticipant.register_idl_type(
        tmsConstants.tms_AuthorizationToEnergizeRequest,
        "tms::AuthorizationToEnergizeRequest")
    dds.DomainParticipant.register_idl_type(
        tmsConstants.tms_AuthorizationToEnergizeReply,
        "tms::AuthorizationToEnergizeReply")
    dds.DomainParticipant.register_idl_type(
        tmsConstants.tms_AuthorizationToEnergizeResult,
        "tms::AuthorizationToEnergizeResult")
    dds.DomainParticipant.register_idl_type(
        tmsConstants.tms_EnergyStartStopState, "tms::EnergyStartStopState")
    dds.DomainParticipant.register_idl_type(
        tmsConstants.tms_EnergyStartStopRequest, "tms::EnergyStartStopRequest")
    dds.DomainParticipant.register_idl_type(
        tmsConstants.tms_Reply, "tms::Reply")


# ---------------------------------------------------------------------------
# Writer listener
# ---------------------------------------------------------------------------

class DefaultWriterListener(dds.NoOpDataWriterListener):
    def on_publication_matched(self, writer, status):
        logging.info('%s Listener Callback On Publication Match ', writer.topic_name)
        logging.info("{0} Writer Subs: {1} {2}".
                     format(writer.topic_name,
                            status.current_count,
                            status.current_count_change))


# ---------------------------------------------------------------------------
# Writer base class  (compiled-types version)
# ---------------------------------------------------------------------------

class Writer(Thread):
    """Base writer thread.

    Parameters
    ----------
    participant      : dds.DomainParticipant  – created from XML config
    periodic         : bool  – if True the thread writes on a timer
    period           : float – seconds between writes (used when periodic=True)
    topic_type_class : type  – the compiled @idl.struct class for this topic
                               (e.g. tmsConstants.tms_Heartbeat)
    writer_name      : str   – entity path used to look up the DataWriter,
                               e.g. "GD_Publisher::HeartbeatWriter"
    """

    def __init__(self, participant, periodic, period, topic_type_class, writer_name):
        Thread.__init__(self)
        self._topic_type_class = topic_type_class
        self._topic_type_name  = topic_type_class.__name__   # used in log msgs
        self._writer_name      = writer_name
        self._periodic         = periodic
        self._period           = period

        # Instantiate a typed sample using the compiled type class
        self._sample = topic_type_class()

        # Locate the DataWriter created by XML App Creation and wrap it for
        # typed (compiled-type) access.
        self._writer = dds.DataWriter(
            participant.find_datawriter(self._writer_name))

        self._status_condition = dds.StatusCondition(self._writer)
        self._status_condition.enabled_statuses = dds.StatusMask.PUBLICATION_MATCHED
        self._waitset = dds.WaitSet()
        self._waitset += self._status_condition
        # Store period as a dds.Duration so WaitSet.wait() accepts it
        self._wait_duration = dds.Duration(seconds=int(self._period),
                                           nanoseconds=int(
                                               (self._period % 1) * 1_000_000_000))
        logging.info("Writer Topic {w_name} created".format(w_name=self._writer_name))

    def run(self):  # Thread of execution – overrides threading.Thread
        logging.info("Writer Thread running for {w_name}".format(
            w_name=self._writer_name))
        while application.run_flag:
            condition = self._waitset.wait(self._wait_duration)
            if self._status_condition in condition:
                status_mask = self._writer.status_changes
                st = self._writer.publication_matched_status
                if dds.StatusMask.PUBLICATION_MATCHED in status_mask:
                    logging.info("{0} Writer Subs: {1} {2}".format(
                        self._topic_type_name,
                        st.current_count,
                        st.current_count_change))

            elif self._periodic:  # no active condition – check if periodic
                self.write()

    # Optionally override in the concrete topic class
    def write(self):
        logging.info('Writing (Default Writer) - %s ', self._topic_type_name)
        self._writer.write(self._sample)

    @property
    def writer(self):
        return self._writer

    def join(self):
        super().join()

    # ***  OVERRIDE IN CONCRETE TOPIC CLASS TO SET TOPIC-SPECIFIC FIELDS
    def handler(self):
        logging.info("DEFAULT WRITER HANDLER FOR {w_name} NOT SET ".format(
            w_name=self._writer_name))
        logging.info("*** OVERRIDE TO SET STATIC TOPIC VALUES")

    @classmethod
    def enable(cls):
        _enabled = True  # noqa: F841

    @classmethod
    def disable(cls):
        _enabled = False  # noqa: F841


# ---------------------------------------------------------------------------
# Reader base class  (compiled-types version)
# ---------------------------------------------------------------------------

class Reader(Thread):
    """Base reader thread.

    Parameters
    ----------
    participant      : dds.DomainParticipant  – created from XML config
    topic_type_class : type  – the compiled @idl.struct class for this topic
    reader_name      : str   – entity path used to look up the DataReader,
                               e.g. "GD_Subscriber::HeartbeatReader"
    """

    def __init__(self, participant, topic_type_class, reader_name):
        Thread.__init__(self)
        self._participant      = participant
        self._topic_type_class = topic_type_class
        self._topic_type_name  = topic_type_class.__name__   # used in log msgs
        self._reader_name      = reader_name

        # Locate the DataReader created by XML App Creation and wrap it for
        # typed (compiled-type) access.
        self._reader = dds.DataReader(
            participant.find_datareader(self._reader_name))

        # Create a ReadCondition to receive any data
        self._read_condition = dds.ReadCondition(
            self._reader, dds.DataState.any_data)

        self._status_condition = dds.StatusCondition(self._reader)
        self._status_condition.enabled_statuses = dds.StatusMask.SUBSCRIPTION_MATCHED

        self._waitset = dds.WaitSet()
        self._waitset += self._status_condition
        self._waitset += self._read_condition
        # Fixed 4-second receive timeout as a dds.Duration
        self._wait_duration = dds.Duration(seconds=4)
        logging.info("Reader Topic {r_name} created".format(r_name=self._reader_name))

    def run(self):  # Thread of execution – overrides threading.Thread
        logging.info("Reader Thread running for {r_name}".format(
            r_name=self._reader_name))
        while application.run_flag:
            condition = self._waitset.wait(self._wait_duration)
            if self._status_condition in condition:
                status_mask = self._reader.status_changes
                st = self._reader.subscription_matched_status
                if dds.StatusMask.SUBSCRIPTION_MATCHED in status_mask:
                    logging.info("{0} Reader Pubs: {1} {2}".format(
                        self._topic_type_name,
                        st.current_count,
                        st.current_count_change))

            if self._read_condition in condition:
                # With compiled types, data is a typed Python instance
                for (data, info) in filter(
                        lambda s: s.info.valid, self._reader.take()):
                    self.handler(data)

    def join(self):
        super().join()

    # *** MUST OVERRIDE IN CONCRETE TOPIC CLASS TO HANDLE RECEIVED SAMPLES ***
    def handler(self, data):
        logging.info("DEFAULT READER HANDLER FOR {r_name}  ".format(
            r_name=self._reader_name))
        logging.info("*** OVERRIDE TO READ SPECIFIC TOPIC VALUES")
        logging.info(data)

    def get_reader_handle(self):
        return self._reader
